#!/bin/bash

rm -rf summaries/*

i=1
offenses="all_other_offenses arson assault breaking_and_entering
          burglary counterfeiting destruction_of_property disorderly_conduc
          dui drug drunkenness embezzlement homicide kidnapping larceny
          liquor_law_violations motor_vehicle_theft peeping_tom
          pornography robbery runaway sex_offenses disorderly_conduct"

for offense in $offenses
do
	sed -n "s/^$((i++)),[^,]*,\([^,]*\),.*/\1/p" * > summaries/$offense
done
